/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffmm;

/**
 *
 * @author ZuluCorp
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnidepositos = new javax.swing.JMenuItem();
        mnisaldos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniintanuales = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniinfdepositos = new javax.swing.JMenuItem();
        mniinfsaldos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpescritorioLayout = new javax.swing.GroupLayout(jdpescritorio);
        jdpescritorio.setLayout(jdpescritorioLayout);
        jdpescritorioLayout.setHorizontalGroup(
            jdpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpescritorioLayout.setVerticalGroup(
            jdpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operaciones");

        mnidepositos.setText("Depósitos");
        mnidepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidepositosActionPerformed(evt);
            }
        });
        jMenu2.add(mnidepositos);

        mnisaldos.setText("Saldos");
        mnisaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisaldosActionPerformed(evt);
            }
        });
        jMenu2.add(mnisaldos);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Intereses");

        mniintanuales.setText("Anuales");
        jMenu4.add(mniintanuales);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Informes");

        mniinfdepositos.setText("Depósitos");
        jMenu3.add(mniinfdepositos);

        mniinfsaldos.setText("Saldos");
        jMenu3.add(mniinfsaldos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnidepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidepositosActionPerformed
        Depositos dep= new Depositos();
        jdpescritorio.add(dep);
        dep.show();
    }//GEN-LAST:event_mnidepositosActionPerformed

    private void mnisaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisaldosActionPerformed
        Saldos sal= new Saldos();
        jdpescritorio.add(sal);
        sal.show();
    }//GEN-LAST:event_mnisaldosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpescritorio;
    private javax.swing.JMenuItem mnidepositos;
    private javax.swing.JMenuItem mniinfdepositos;
    private javax.swing.JMenuItem mniinfsaldos;
    private javax.swing.JMenuItem mniintanuales;
    private javax.swing.JMenuItem mnisaldos;
    // End of variables declaration//GEN-END:variables
}
