/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Clases.Conecta;
import static Clases.Conecta.conexion;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DarthZulu
 */
public class Saldos extends javax.swing.JPanel {

    /**
     * Creates new form Saldoss
     */
    public Saldos() {
        initComponents();
        //setTitle("Ventana Saldos");
        //mostrar ventana
        //this.setLocation(268, 55);
        //x = "x";
        //setVisible(true);
        
        
        mostrardatos("");
        anchocolumnas();
        CargarCbma();
        Cargartxtma();
        cbma.setVisible(false);
        //calendar.getDateEditor().setEnabled(false);
        txtdiferencia.setText("0");
        /*DefaultTableModel tbsaldos = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                if (columna > 3) {
                    return true;
                }
                return false;
            }
            };*/
        txtmonto.setText("0");
    }
/*private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {                                          
        x = null;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        btlimpiar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        btinsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        calendar = new rojeru_san.componentes.RSDateChooser();
        cbma = new javax.swing.JComboBox();
        txtsa = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        txtdiferencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsaldos = new rojeru_san.complementos.RSTableMetro();
        jPanel6 = new javax.swing.JPanel();

        btlimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btlimpiar.setText("Limpiar");

        bteliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bteliminar.setText("Eliminar");

        btmodificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmodificar.setText("Modificar");

        btinsertar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btinsertar.setText("Insertar");
        btinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Fecha");

        calendar.setColorBackground(new java.awt.Color(30, 190, 165));
        calendar.setFormatoFecha("dd-MM-yyyy");

        cbma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtsa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsa.setEnabled(false);

        txtmonto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtmonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmontoFocusLost(evt);
            }
        });

        txtdiferencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtdiferencia.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Diferencia");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Monto Actual");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Monto Anterior");

        tbsaldos = new rojeru_san.complementos.RSTableMetro() {
            public boolean isCellEditable(int rowIndex, int cellIndex){
                return false;
            }
        };
        tbsaldos.getTableHeader().setReorderingAllowed(false);
        tbsaldos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbsaldos.setColorBackgoundHead(new java.awt.Color(30, 190, 165));
        tbsaldos.setFuenteHead(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(tbsaldos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbma, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btlimpiar)
                                    .addComponent(btmodificar)
                                    .addComponent(btinsertar)
                                    .addComponent(bteliminar))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btinsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bteliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btlimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Scotiabank", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("BancoEstado", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents
void mostrardatos(String valor) {
        /*Date fc = calendar.getDate();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd-MM-yyyy");
        String fec = "" + formatofecha.format(fc);*/
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Monto Saldo");
        modelo.addColumn("Monto Diferencia");
        tbsaldos.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT Fecha,Monto,Diferencia FROM saldos ORDER BY ID desc";
        } else {
            //sql = "SELECT * FROM saldos WHERE Fecha='" + fec + "' ORDER BY ID desc";
        }

        String[] datos = new String[3];
        try {
            conexion = Conecta.getConexion();
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                DecimalFormat formatea = new DecimalFormat("###,###.##");
                datos[0] = rs.getString(1);
                datos[1] = "$  "+(formatea.format(rs.getInt(2)));
                datos[2] = "$  "+(formatea.format(rs.getInt(3)));
                modelo.addRow(datos);
            }
            tbsaldos.setModel(modelo);
            //tbsaldos.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage().toString());
        }
    }
    
    void anchocolumnas() {
        tbsaldos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tbsaldos.getColumnModel().getColumn(0).setWidth(100);
        tbsaldos.getColumnModel().getColumn(0).setMaxWidth(100);
        tbsaldos.getColumnModel().getColumn(0).setMinWidth(100);
        
        tbsaldos.getColumnModel().getColumn(1).setWidth(150);
        tbsaldos.getColumnModel().getColumn(1).setMaxWidth(150);
        tbsaldos.getColumnModel().getColumn(1).setMinWidth(150);
        
        tbsaldos.getColumnModel().getColumn(2).setWidth(150);
        tbsaldos.getColumnModel().getColumn(2).setMaxWidth(150);
        tbsaldos.getColumnModel().getColumn(2).setMinWidth(150);
    }
    
    private void CargarCbma(){
        //Carga de Combo
        try {
            conexion = Conecta.getConexion();
            Statement st = conexion.createStatement();
            String sql = "SELECT max(ID) FROM saldos";
            //Ejecutar consulta
            ResultSet rs = st.executeQuery(sql);
            //Limpiamos el Combo
            cbma.setModel(new DefaultComboBoxModel());
            //Recorremos los registros traidos
            while (rs.next()) {
                //Agregamos elemento al combo
                cbma.addItem(rs.getObject(1));
            }
            //Cerramos conexión
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage().toString());
        }
    }
    
     private void Cargartxtma(){
        //Carga de Combo
         try {
             conexion = Conecta.getConexion();
             Statement st1 = conexion.createStatement();
             String sql1 = "SELECT Monto FROM saldos WHERE ID='" + cbma.getSelectedItem() + "'";
             //Ejecutar consulta
             ResultSet rs1 = st1.executeQuery(sql1);
             //Recorremos los registros traidos
             while (rs1.next()) {
                 //Agregamos elemento al text
                 txtsa.setText(rs1.getObject("Monto").toString());
             }
             //Cerramos conexión
             conexion.close();
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error " + e.getMessage().toString());
         }
    }
     
    void calculadiferencia(){
        String ma = txtsa.getText();
        String mn = txtmonto.getText();
        int ent1 = Integer.parseInt(ma);
        int ent2 = Integer.parseInt(mn);
        int resta = (ent2-ent1);
        txtdiferencia.setText(String.valueOf(resta));
    }
    
    private String validarVacios() {
        String errores = "";
        if(calendar.getDatoFecha()== null){
            errores += "Por favor ingrese la fecha \n";
        }
        if(txtmonto.getText().equals("")){
            errores += "Por favor ingrese el Monto del Día \n";
        }
        if(txtdiferencia.getText().trim().isEmpty()){
            errores += "El campo diferencia está vacio \n";
        }
        return errores;       
    }
    
    private void txtmontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmontoFocusLost
        calculadiferencia();
    }//GEN-LAST:event_txtmontoFocusLost

    private void btinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertarActionPerformed
        String errores = validarVacios();
        if (errores.equals("")) {
            try {
                Date fc = calendar.getDatoFecha();
                DateFormat fecha = new SimpleDateFormat("dd-MM-yyyy");
                String convertido = fecha.format(fc);
                conexion = Conecta.getConexion();
                //crear la consulta
                Statement st = conexion.createStatement();
                //crear variable tipo string
                String sql = "INSERT INTO saldos (Fecha,Monto,Diferencia) "
                + "VALUES('" + convertido + "','" + txtmonto.getText() + "','" + txtdiferencia.getText() + "')";
                //ejecutar consulta
                st.executeUpdate(sql);
                //cerrar conexion
                conexion.close();
                //Mostrar mensaje al usuario
                JOptionPane.showMessageDialog(this, "Saldo Ingresado");
                //limpiar los campos
                //calendar.setText("");
                txtmonto.setText("");
                txtdiferencia.setText("");
                mostrardatos("");
                anchocolumnas();
                //dar foco a fecha
                calendar.requestFocus();
            } catch (Exception e) {
                //mensaje de error que declara la base de datos
                JOptionPane.showMessageDialog(this, "ERROR" + e.getMessage().toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, errores);
        }
    }//GEN-LAST:event_btinsertarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btinsertar;
    private javax.swing.JButton btlimpiar;
    private javax.swing.JButton btmodificar;
    private rojeru_san.componentes.RSDateChooser calendar;
    private javax.swing.JComboBox cbma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private rojeru_san.complementos.RSTableMetro tbsaldos;
    private javax.swing.JTextField txtdiferencia;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtsa;
    // End of variables declaration//GEN-END:variables
}
